In [15]:
import numpy as np

Creating arrays

In [16]:
np.zeros(4)

array([0., 0., 0., 0.])

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [19]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [20]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [21]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [22]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [23]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [24]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
a[1,0]

np.int64(4)

In [34]:
a[:, 0]

array([1, 4, 7])

In [36]:
#randomly generated arrays
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])